#! /usr/bin/env sh


wget -q http://172.30.201.20/api/v4/grapher/mrtg-config?apikey=daEpzL0faxeFHDPGP3JmXDutMQTMZxOlzk7LErYnIGUBK2Zt -O /etc/mrtg.cfg.$$

if [[ $? -ne 0 ]]; then
    echo "WARNING: COULD NOT FETCH UP TO DATE MRTG CONFIGURATION!"
    rm -f /etc/mrtg.cfg.$$
    exit -1
fi

cd /etc

sed -i -e 's/RunAsDaemon:Yes/RunAsDaemon:No/g' /etc/mrtg.cfg.$$


cat mrtg.cfg    | egrep -v '^#.*$' | egrep -v '^[ ]+Based on configuration last generated by.*$' >mrtg.cfg.filtered
cat mrtg.cfg.$$ | egrep -v '^#.*$' | egrep -v '^[ ]+Based on configuration last generated by.*$' >mrtg.cfg.$$.filtered
diff mrtg.cfg.filtered mrtg.cfg.$$.filtered >/dev/null
DIFF=$?

rm mrtg.cfg.filtered
rm mrtg.cfg.$$.filtered

if [[ $DIFF -eq 0 ]]; then
    rm mrtg.cfg.$$
    exit 0
fi

/usr/bin/mrtg --check /etc/mrtg.cfg.$$                 \
    && /bin/mv /etc/mrtg.cfg.$$ /etc/mrtg.cfg
